#pragma once
void test_create_list_of_tranzactions();
void test_destroy_struct_with_field_tranzactions();
void test_copie_struct_obj();
void test_add_tranzaction_repo();
void test_delete_tranzaction_repo();
void test_modify_tranzaction_repo();
void test_get_next_tranzaction_id();
void test_resize();